name: WarpedWither
version: '1.0'
main: me.lninyu.warpedWither.WarpedWither
api-version: '1.21'

libraries:
    - "com.zaxxer:HikariCP:7.0.2"
    - "com.mysql:mysql-connector-j:9.6.0"
    - "com.github.ben-manes.caffeine:caffeine:3.2.3"
